import type { Metadata } from "next";
import { Lexend_Exa } from 'next/font/google';
import "./globals.css";

const lexendExa = Lexend_Exa({
  subsets: ['latin'],
  weight: ['100', '200', '300'],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-BR">
      <body className={lexendExa.className}>{children}</body>
    </html>
  );
}